<template>
  <section class="blog">
    <div class="blog__container">
      <Title class="blog__title" title="Will be on the next week..." />
      <div class="loadingio-spinner-bean-eater-laf79t3nl4">
        <div class="ldio-nanki2cech">
          <div>
            <div></div>
            <div></div>
            <div></div>
          </div>
          <div>
            <div></div>
            <div></div>
            <div></div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import Title from "../common/Title.vue";
export default {
  components: { Title },
  name: "Blog",
};
</script>

<style lang="scss">
.blog {
  &__container {
    @include flex(center, center, column);
    padding: 30px 0 15px;
    @include media {
      padding: 75px 0;
    }
  }
  &__title {
    margin-bottom: 20px;
  }
}
</style>

<style type="text/css" >
@keyframes ldio-nanki2cech-1 {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(-45deg);
  }
  100% {
    transform: rotate(0deg);
  }
}
@keyframes ldio-nanki2cech-2 {
  0% {
    transform: rotate(180deg);
  }
  50% {
    transform: rotate(225deg);
  }
  100% {
    transform: rotate(180deg);
  }
}
.ldio-nanki2cech > div:nth-child(2) {
  transform: translate(-15px, 0);
}
.ldio-nanki2cech > div:nth-child(2) div {
  position: absolute;
  top: 40px;
  left: 40px;
  width: 120px;
  height: 60px;
  border-radius: 120px 120px 0 0;
  background: #7beec7;
  animation: ldio-nanki2cech-1 1s linear infinite;
  transform-origin: 60px 60px;
}
.ldio-nanki2cech > div:nth-child(2) div:nth-child(2) {
  animation: ldio-nanki2cech-2 1s linear infinite;
}
.ldio-nanki2cech > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}
@keyframes ldio-nanki2cech-3 {
  0% {
    transform: translate(190px, 0);
    opacity: 0;
  }
  20% {
    opacity: 1;
  }
  100% {
    transform: translate(70px, 0);
    opacity: 1;
  }
}
.ldio-nanki2cech > div:nth-child(1) {
  display: block;
}
.ldio-nanki2cech > div:nth-child(1) div {
  position: absolute;
  top: 92px;
  left: -8px;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: #60606e;
  animation: ldio-nanki2cech-3 1s linear infinite;
}
.ldio-nanki2cech > div:nth-child(1) div:nth-child(1) {
  animation-delay: -0.67s;
}
.ldio-nanki2cech > div:nth-child(1) div:nth-child(2) {
  animation-delay: -0.33s;
}
.ldio-nanki2cech > div:nth-child(1) div:nth-child(3) {
  animation-delay: 0s;
}
.loadingio-spinner-bean-eater-laf79t3nl4 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-nanki2cech {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-nanki2cech div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>